NetworkExpansion: 1
TimeDomainReductionFolder: "TDR_Results"
ModelingToGenerateAlternativeIterations: 3
ParameterScale: 1
EnergyShareRequirement: 0
PrintModel: 0
TimeDomainReduction: 1
Trans_Loss_Segments: 1
CapacityReserveMargin: 1
ModelingtoGenerateAlternativeSlack: 0.1
MethodofMorris: 0
StorageVirtualDischarge: 1
Reserves: 0
StorageLosses: 1
OverwriteResults: 1
UCommit: 2
ModelingToGenerateAlternatives: 0
MaxCapReq: 1
MinCapReq: 1
CO2Cap: 1
WriteShadowPrices: 1
Benders: 0
LDES_Feasible: 0
IntegerInvestments: 0